---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Install in your local dev environment
# > pip install --upgrade --user pre-commit
# Enable the hooks for this repo
# > pre-commit install

# yamllint disable rule:line-length

# Completely exclude certain files from checks
# exclude: |
#   (?x)^(
#     vendor/.**|
#     dir2/.*
#   )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files  # Prevents giant files from being committed
      - id: check-merge-conflict     # Check merge conflict strings
      - id: check-symlinks           # Ensure symlinks have a valid target
      - id: end-of-file-fixer        # File is empty or ends with one newline
      - id: fix-byte-order-marker    # Forbid utf-8 byte order marker
      - id: trailing-whitespace      # Trims trailing whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      # Forbid UTF-8 replacement character
      - id: text-unicode-replacement-char

  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.38.0"
    hooks:
      # Lint yaml files
      - id: yamllint
        args: ["--strict", "-c", ".github/yamllint-config.yaml"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.47.0"
    hooks:
      # Lint markdown files
      - id: markdownlint
        exclude: |
          (?x)^(
                .github/pull_request_template.md
            )$

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: "43.31.1"
    hooks:
      # Validate Renovate's configuration file
      - id: renovate-config-validator

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      # Prevent secrets from being committed
      - id: detect-secrets
      #  args: ['--baseline', '.secrets.baseline']
      #  exclude: package.lock.json

  - repo: https://gitlab.com/bmares/check-json5
    rev: "v1.0.1"
    hooks:
      # Check that JSON files are valid JSON5
      - id: check-json5
